### ISSUE TITLE
does it support react native?

### ISSUE THREAD

**Issue by thanhnvpk01168** [philnash/react-twilio-phone#21]
Can you tell me if I use this lib and use it for react native, will it work properly?
Hope you can help me, thank you in advance

**Comment by philnash** [comment]
Hi, I have not tried the JS Voice SDK in React Native, so I can't tell you whether it will work or not. But you are welcome to try.

There is also a [React Native wrapper built by the community](https://github.com/hoxfon/react-native-twilio-programmable-voice) that you may find works as well.
