### ISSUE TITLE
States

### ISSUE THREAD

**Issue by f-zeee** [philnash/react-twilio-phone#22]
Hey, can you tell me what is the actual function of each of the states?

**Comment by philnash** [comment]
The [states](https://github.com/philnash/react-twilio-phone/blob/master/src/states.js) are:

```js
const states = {
  CONNECTING: "Connecting",
  READY: "Ready",
  INCOMING: "Incoming",
  ON_CALL: "On call",
  OFFLINE: "Offline"
};
```

Connecting is as the device is preparing.
Ready means it is ready to make or receive a call.
Incoming means there is an incoming call.
On call means that there is a current live call that has been answered.
Offline means the device has disconnected.

Does that help?

**Comment by f-zeee** [comment]
Yes thank you!
